export const tempData = [
  // { completed: true, task: "Clean kitschen", category: "home" },
  // { completed: false, task: "Buy Groceries", category: "home" },
  // { completed: false, task: "Change betsheets", category: "home" },
  // { completed: false, task: "Take out trash", category: "home" },
  // { completed: true, task: "Clean Basement", category: "home" },
  // { completed: false, task: "Walk with the dog", category: "family" },
  // { completed: true, task: "Take child to school", category: "family" },
  // {
  //   completed: true,
  //   task: "Go with the wife to the doctor",
  //   category: "family",
  // },
  // { completed: false, task: "Call Parents", category: "family" },
  // { completed: false, task: "Organice familiar meeting", category: "family" },
  // { completed: true, task: "Finish Task component", category: "work" },
  // {
  //   completed: true,
  //   task: "Read new documentation for react-router-dom",
  //   category: "work",
  // },
  // { completed: false, task: "Start at 7:15am in Gorillas", category: "work" },
  // {
  //   completed: false,
  //   task: "Check breaks and weels from the bike",
  //   category: "work",
  // },
  // { completed: true, task: "Play basketball", category: "sports" },
  // { completed: true, task: "Run one hour", category: "sports" },
  // {
  //   completed: false,
  //   task: "Play Ping-Pong with Soonam",
  //   category: "sports",
  // },
];
